### ISSUE TITLE
implementation details

### ISSUE THREAD

**Issue by Nintorac** [wohlert/semi-supervised-pytorch#1]
Hey, cool project

I was wondering..in the dgm notebook you calculate the loss using both the labelled and unlabelled data?

From my understanding there would be a conditional there i.e
```
if labelled:
    use loss method a)
else: 
    use loss method b)
```
However you seem to calculate the loss for one batch of each and sum them?

Is there any benefit to doing it this way as opposed to simply picking which dataset to use on each iteration? 

Cheers

**Comment by wohlert** [comment]
That is correct. I have addressed this with the addition of the `trainers` API. A new notebook should follow at the end of this week.

Thank you for the feedback.
