### ISSUE TITLE
RuntimeError: size mismatch at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/generic/THCTensorMathBlas.cu:243

### ISSUE THREAD

**Issue by huanyii** [wohlert/semi-supervised-pytorch#10]
When I ran 'Auxiliary Deep Generative Model.ipynb', I met this problem:
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-a3bbc49c191b> in <module>()
     13             u = u.cuda(device=0)
     14 
---> 15         L = -elbo(x, y)
     16         U = -elbo(u)
     17 

~/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    323         for hook in self._forward_pre_hooks.values():
    324             hook(self, input)
--> 325         result = self.forward(*input, **kwargs)
    326         for hook in self._forward_hooks.values():
    327             hook_result = hook(self, input, result)

~/code/baidu/semi-supervised-pytorch/semi-supervised/inference/variational.py in forward(self, x, y)
     86         ys = self.sampler.resample(ys)
     87 
---> 88         reconstruction = self.model(xs, ys)
     89 
     90         # p(x|y,z)

~/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    323         for hook in self._forward_pre_hooks.values():
    324             hook(self, input)
--> 325         result = self.forward(*input, **kwargs)
    326         for hook in self._forward_hooks.values():
    327             hook_result = hook(self, input, result)

~/code/baidu/semi-supervised-pytorch/semi-supervised/models/dgm.py in forward(self, x, y)
    155 
    156         # Latent inference q(z|a,y,x)
--> 157         z, z_mu, z_log_var = self.encoder(torch.cat([x, y, q_a], dim=1))
    158 
    159         # Generative p(x|z,y)

~/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    323         for hook in self._forward_pre_hooks.values():
    324             hook(self, input)
--> 325         result = self.forward(*input, **kwargs)
    326         for hook in self._forward_hooks.values():
    327             hook_result = hook(self, input, result)

~/code/baidu/semi-supervised-pytorch/semi-supervised/models/vae.py in forward(self, x)
     55     def forward(self, x):
     56         for layer in self.hidden:
---> 57             x = F.relu(layer(x))
     58         return self.sample(x)
     59 

~/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    323         for hook in self._forward_pre_hooks.values():
    324             hook(self, input)
--> 325         result = self.forward(*input, **kwargs)
    326         for hook in self._forward_hooks.values():
    327             hook_result = hook(self, input, result)

~/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/linear.py in forward(self, input)
     53 
     54     def forward(self, input):
---> 55         return F.linear(input, self.weight, self.bias)
     56 
     57     def __repr__(self):

~/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py in linear(input, weight, bias)
    833     if input.dim() == 2 and bias is not None:
    834         # fused op is marginally faster
--> 835         return torch.addmm(bias, input, weight.t())
    836 
    837     output = input.matmul(weight.t())

RuntimeError: size mismatch at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/generic/THCTensorMathBlas.cu:243

Can you give me some suggestion? What's more, I wanna know the version of pytorch in your code and I'm using the version pytorch-0.3.0-cuda80.

**Comment by wohlert** [comment]
If you didn't change anything in the notebook then I find this error strange. It looks like the number of neurons in the hidden layer of the encoder for the z variable does not match, in any case it needs an input of size x.size() + y.size() + a.size(). I think I used `pytorch-0.3.0` back when I developed it, but I recently had students make it work with `pytorch-1.0.0` (though with some warnings).
