### ISSUE TITLE
when python3 betavae.py，sampler option is mutually exclusive with shuffle

### ISSUE THREAD

**Issue by oldbaldhead** [wohlert/semi-supervised-pytorch#12]
File "C:\Users\ibing\Anaconda3\envs\pytorch-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '

ValueError: sampler option is mutually exclusive with shuffle

**Comment by wohlert** [comment]
This is intended, remove the shuffle argument from the dataloader or set it to 0.
