### ISSUE TITLE
when python mnist_sslvae.py

### ISSUE THREAD

**Issue by oldbaldhead** [wohlert/semi-supervised-pytorch#14]
in shell:"python mnist_sslvae.py"
i choose " from models import LadderDeepGenerativeModel 
                 models += [LadderDeepGenerativeModel([784, n_labels, [32, 16, 8], [128, 128, 128]])]”
i met the problem:
"Traceback (most recent call last):
  File "mnist_sslvae.py", line 117, in <module>
    total_loss += J_alpha.data[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number"

**Comment by oldbaldhead** [comment]
i wonder that
need i change every data[0] to item()?any other solution?

**Comment by wohlert** [comment]
You need to downgrade to PyTorch 0.4.0.

Please stop creating issues for problems not related to the codebase. You can find these solutions on sites like stackoverflow.
