### ISSUE TITLE
Using softplus on logvar in Gaussian_Sample

### ISSUE THREAD

**Issue by Clondon98** [wohlert/semi-supervised-pytorch#16]
Dear wohlert,

I wanted to ask why you use softplus on the logvar in Gaussian sample. Should logvar not be able to take the full range of real numbers as the exponential is greater than zero everywhere? 
https://github.com/wohlert/semi-supervised-pytorch/blob/7cde4959468d271552febdcfed5e1cfae9857613/semi-supervised/layers/stochastic.py#L44

Apologies if this is not the right place to ask, I looked for an email to contact but couldn't find it.
Thanks very much

**Comment by wohlert** [comment]
You are correct, this is a mistake and this is the right place to post it, thanks for finding it. 

I am not sure what the implications are for changing, I think the rationale stems from the use of the regular variance in the Ladder VAE. I will get to it at some point.
