### ISSUE TITLE
Aux Model Decoder

### ISSUE THREAD

**Issue by NightmareNyx** [wohlert/semi-supervised-pytorch#17]
In dmg.py line 131, you do `self.aux_decoder = Encoder([x_dim + z_dim + y_dim, list(reversed(h_dim)), a_dim])`. Do you mean Decoder, or am I missing something?

Thanks

**Comment by wohlert** [comment]
The code is correct, but the naming is perhaps confusing. In this framework any model that returns a Gaussian distribution tuple `(sample, mean, variance)` is an Encoder. As we the parameters of the distribution is required for the auxiliary KL we use an encoder rather than a decoder class.

**Comment by NightmareNyx** [comment]
Okay thanks!
