### ISSUE TITLE
cross_entropy in log_standard_categorical

### ISSUE THREAD

**Issue by rojinsafavi** [wohlert/semi-supervised-pytorch#18]
Hello Wohlert,

Thanks for providing this resource. I was wondering if the cross_entropy in log_standard_categorical function suppose to return the same thing all the time? It seems that it's only returning:
`cross_entropy tensor([2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026,
        2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026,
        2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026,
        2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026,
        2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026,
        2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026,
        2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026, 2.3026,
        2.3026])`

Thank you very much,

Best,
Rojin

**Comment by wohlert** [comment]
Hi Rojin

We consider the standard categorical to mean the categorical distribution with k categories for which the probability of each are equally likely. In our models we use this as our a priori knowledge of the class occurrence as it incurs little bias.

A point of confusion is that [line 42](https://github.com/wohlert/semi-supervised-pytorch/blob/7cde4959468d271552febdcfed5e1cfae9857613/semi-supervised/inference/distributions.py#L42) actually denotes the cross entropy between the distribution and itself, so a better name would be (self-)entropy.

To see why it always returns the same for each datapoint in the batch, we can calculate the entropy for a "standard" categorical with 10 categories:

![]("https://latex.codecogs.com/png.latex?\text{H}[\text{Cat}(1/k)]=-\sum_{i=1}^k\frac{1}{k}\log\left(\frac{1}{k}\right)=\log(k)")

Then `H[cat(10)] = 2.3026`

I hope this clears up any confusion.

**Comment by rojinsafavi** [comment]
Thank you very much Wohlert 🙏🙏🙏
