### ISSUE TITLE
prediction

### ISSUE THREAD

**Issue by rojinsafavi** [wohlert/semi-supervised-pytorch#19]
Dear Wohlert,

I was wondering if it is possible to apply the semi-supervised model to a single prediction task( like a regression prediction) and not a classification? basically replacing the classification part with a regression task (MLP with one output node that predicts a value)?

Best regards,
Rojin

**Comment by wohlert** [comment]
In theory you can replace the partially observed y with a continuous variable, but then the sum trick no longer applies and you will have to compute a very difficult integral over the labelled ELBO. You could approximate this instead, but this would likely lead to high variance and bad training.

You can find the original paper [here](https://papers.nips.cc/paper/5352-semi-supervised-learning-with-deep-generative-models.pdf), specifically section 3.1.2, maybe you can work out something.

In general this thing is outside the realm of semi-supervised learning.
