### ISSUE TITLE
Decoder layer 

### ISSUE THREAD

**Issue by xiayzh** [wohlert/semi-supervised-pytorch#22]
Hello, I have a question for the code in ladder decoder layer.
In each ladder decoder, why there are  two different NNs( self.linear1 and self.linear2) to compute mu sigma for merging and sampling,
```
self.linear1 = nn.Linear(x_dim, h_dim)
 self.batchnorm1 = nn.BatchNorm1d(h_dim)
 self.merge = GaussianMerge(h_dim, self.z_dim)

self.linear2 = nn.Linear(x_dim, h_dim)
self.batchnorm2 = nn.BatchNorm1d(h_dim)
self.sample = GaussianSample(h_dim, self.z_dim)
```
```
z = self.linear1(x)
z = F.leaky_relu(self.batchnorm1(z), 0.1)
q_z, q_mu, q_log_var = self.merge(z, l_mu, l_log_var)

 z = self.linear2(x)
z = F.leaky_relu(self.batchnorm2(z), 0.1)
z, p_mu, p_log_var = self.sample(z)
```
 rather than  using tha same module
```
z = self.linear1(x)
z = F.leaky_relu(self.batchnorm1(z), 0.1)
q_z, q_mu, q_log_var = self.merge(z, l_mu, l_log_var)
z, p_mu, p_log_var = self.sample(z)
```

**Comment by wohlert** [comment]
Because one defines the recognition (q) model and the other the generative model (p). These are two very separate models and using the same layer will induce correlations that are not intended. You can look up the paper to see why.

**Comment by xiayzh** [comment]
> Because one defines the recognition (q) model and the other the generative model (p). These are two very separate models and using the same layer will induce correlations that are not intended. You can look up the paper to see why.

Thanks a lot! I got it!
