### ISSUE TITLE
Conditional generation and  Accuracy 

### ISSUE THREAD

**Issue by sanlb** [wohlert/semi-supervised-pytorch#25]
I try to run the example of Deep Generative Model(in Deep Generative Model.ipynb). But I find that the imgs are very blurry in the part of Conditional generation, while the example looks ok. And the accuracy of validation is just only 0.7-0.8 in M1 and M1+M2(far away the paper's).

Could you tell me the version of pytorch? There are some errors in get_mnist(). This is pytorch 0.4.1.
Thank you.

**Comment by wohlert** [comment]
The code was originally written for PyTorch 0.3.0 (https://github.com/wohlert/semi-supervised-pytorch/issues/5) and still hasn't been updated - there might be breaking changes. You can try this version and report back if you still see errors.

**Comment by sanlb** [comment]
Thanks for your reply.  It did solve my problem.
