### ISSUE TITLE
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #4 'mat1'

### ISSUE THREAD

**Issue by ucsky** [wohlert/semi-supervised-pytorch#7]
When I try to run the notebook **Auxiliary Deep Generative Model**, at the cell:

    from sesutils import onehot
    model.eval()
    z = Variable(torch.randn(16, 32))
    # Generate a batch of 5s
    y = Variable(onehot(10)(5).repeat(16, 1))
    x_mu = model.sample(z, y)

I get the error:  

    ---------------------------------------------------------------------------
    RuntimeError                              Traceback (most recent call last)
    <ipython-input-6-e78d4b83d3dc> in <module>()
          7 y = Variable(onehot(10)(5).repeat(16, 1))
          8 
    ----> 9 x_mu = model.sample(z, y)
    ~/test/semi-supervised-pytorch-ucsky/semi-supervised/models/dgm.py in sample(self, z, y)
         75         """
         76         y = y.float()
    ---> 77         x = self.decoder(torch.cat([z, y], dim=1))
         78         return x
         79 
    /usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
        489             result = self._slow_forward(*input, **kwargs)
        490         else:
    --> 491             result = self.forward(*input, **kwargs)
       492         for hook in self._forward_hooks.values():
        493             hook_result = hook(self, input, result)

    ~/test/semi-supervised-pytorch-ucsky/semi-supervised/models/vae.py in forward(self, x)
         86     def forward(self, x):
         87         for layer in self.hidden:
    ---> 88             x = F.relu(layer(x))
         89         return self.output_activation(self.reconstruction(x))
         90 
    /usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
        489             result = self._slow_forward(*input, **kwargs)
        490         else:
    --> 491             result = self.forward(*input, **kwargs)
        492         for hook in self._forward_hooks.values():
        493             hook_result = hook(self, input, result)
    /usr/local/lib/python3.5/dist-packages/torch/nn/modules/linear.py in forward(self, input)
         53 
         54     def forward(self, input):
    ---> 55         return F.linear(input, self.weight, self.bias)
         56 
         57     def extra_repr(self):
    /usr/local/lib/python3.5/dist-packages/torch/nn/functional.py in linear(input, weight, bias)
        990     if input.dim() == 2 and bias is not None:
        991         # fused op is marginally faster
    --> 992         return torch.addmm(bias, input, weight.t())
        993 
        994     output = input.matmul(weight.t())
    RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #4 'mat1'

**Comment by wohlert** [comment]
It looks like your model is located on the GPU, meaning that you have called `model = model.cuda()`, however the variables y and z you have created are not on the GPU, so you need to call `x, y = x.cuda(), y.cuda()`.
